<?php

namespace Database\Seeders;

use App\Enums\UserTypeEnums;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Maklad\Permission\Models\Permission;
use Maklad\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     * @throws \ReflectionException
     */
    public function run(): void
    {
        app()['cache']->forget('maklad.permission.cache');

        /*$permissions = collect([
            'MASTER',
            'GENERAL MASTER',
            'UOM MASTER',
            'ITEM MAKE MASTER',
            'STORE MASTER',
            'TEST CERTIFICATE TYPE',
            'PARTY TYPE',
            'BUSINESS TYPE MASTER',
            'COUNTRY MASTER',
            'STATE MASTER',
            'CITY MASTER',
            'CURRENCY MASTER',
            'DEPARTMENT',
            'DESIGNATION',
            'ENQUIRY REFERENCE MASTER',
            'QUOTATION TYPE',
            'SALES STAGE TITLE MASTER',
            'SALES LEAD TITLE MASTER',
            'INDUSTRIES TYPE MASTER',
            'REASON MASTER',
            'PURCHASE TYPE',
            'DOCUMENT HEADER',
            'DOCUMENT FOOTER',
            'NOTE MASTER',
            'MACHINE MASTER',
            'PROCESS MASTER',
            'OPERATOR MASTER',
            'BANK MASTER',
            'PACKING MASTER',
            'PAYMENT DEDUCTION MASTER',
            'EXPENSE MASTER',
            'DOCUMENT TYPE MASTER',
            'BRANCH MASTER',
            'PARTY MASTER',
            'PARTY GROUP MASTER',
            'INVOICE TYPE MASTER',
            'SALES ORDER TYPE MASTER',
            'ITEM MASTER',
            'ITEM CATEGORY',
            'ITEM GROUP',
            'MAIN GROUP/SUB GROUP',
            'HSN/SAC MASTER',
            'MATERIAL SPECIFICATION',
            'BILLING DESCRIPTION MASTER',
            'BILLING TEMPLATE MASTER',
            'ADDON TYPE',
            'ADDON DETAIL',
            'ITEM SERIAL NO GENERATION PARAMETERS',
            'SALES TARGET ITEM GROUP',
            'TERM & CONDITION GROUP',
            'TERM & CONDITION DETAILS',
            'DEFAULT TERM & CONDITION',
            'TAX MASTER',
            'TAX FORMS',
            'ISO/API DOCUMENT',
            'DUTY DRAWBACK TARIFF MASTER',
            'IMPORT ITEM MASTER FROM EXCEL',
            'IMPORT PARTY MASTER FROM EXCEL',
            'TASK MANAGER',
            'PROGRESS STAGE MASTER',
            'SERIAL MASTER',
            'MASTER REPORTS',
            'SALES & CRM',
            'SALES SUPPORT',
            'SALES OPPORTUNITIES/LEADS',
            'SALES ENQUIRY',
            'SALES QUOTATION',
            'SALES QUOTATION APPROVAL',
            'SALES ORDER',
            'PROFORMA INVOICE',
            'SALES RETURN - CREDIT NOTE',
            'SALES BRANCHES',
            'SALES OFFICES',
            'SALES COSTING MASTER',
            'SALES COSTING TEMPLATES',
            'SALES DATA HISTORY',
            'SALES TARGET',
            'ITEM RATE MATER',
            'PRICE LIST (PARTY TYPE)',
            'PRICE LIST (PARTY TYPE - ITEM WISE)',
            'PRICE LIST TYPE MASTER',
            'PRICE LIST TYPE WISE',
            'PAYMENT RECEIPT',
            'PROJECT MANAGEMENT',
            'COMPETITOR MASTER',
            'SALES REPORTS',
            'PRODUCTION PLANNING',
            'WORK ORDER',
            'JOB CARD',
            'PROCESS SHEET',
            'ASSEMBLY CARD',
            'ITEM REQUISITION',
            'ADVANCE PLANNING',
            'PRODUCTION FORECASTING',
            'APPROVE WORK ORDER FOR PRODUCTION',
            'JOB CARD MATERIAL RETURN FROM SHOP',
            'JOB CARD PROCESS SUMMARY',
            'WORK ORDER PROCESS SUMMARY',
            'WORK ORDER ITEM SERIAL NOS.',
            'GENERATE WO AGAINST SO',
            'CANCEL/SHORT CLOSE WORK ORDER AGAINST SO',
            'PRODUCTION PLANNING REPORTS',
            'ENGINEERING & BOM',
            'BILL OF MATERIAL',
            'REPLACE ITEM IN BOM',
            'REPLACE SALES ORDER ITEMS',
            'DRAWING MASTER',
            'BOM REPORTS',
            'MRP',
            'WO SHORTAGE (PURCHASE ITEMS) - CUMULATIVE',
            'WO SHORTAGE (ASSEMBLY/COMPONENTS) - CUMULATIVE',
            'MINIMUM LEVEL SHORTAGE',
            'MANUAL PLANNING',
            'WO SHORTAGE (PURCHASE ITEMS) - WO WISE',
            'WO SHORTAGE (ASSEMBLY/COMPONENTS) - WO WISE',
            'PENDING INDENT',
            'INDENT APPROVAL',
            'FORECAST BASE SHORTAGE',
            'MRP REPORT',
            'PURCHASE',
            'PURCHASE ORDER AGAINST INDENT',
            'PURCHASE ORDER',
            'PURCHASE ORDER APPROVAL',
            'PURCHASE COSTING',
            'PURCHASE RETURN - DEBIT NOTE',
            'PURCHASE CARD (ITEM WISE)',
            'PURCHASE CARD (PARTY WISE)',
            'ITEM RATE MASTER (PURCHASE)',
            'VENDOR RATING PARAMETERS',
            'PURCHASE ENQUIRY',
            'PURCHASE QUOTATION',
            'PURCHASE REPORT',
            'JOB WORK',
            'JOB WORK ORDER',
            'ISSUE (JOB WORK CHALLAN)',
            'RECEIPT (JOB WORK CHALLAN)',
            'RAW MATERIAL RETURN FROM SUB - CONTRACTOR',
            'SCRAP RECEIPT ENTRY',
            'JOB WORK REWORK CHALLAN',
            'JOB WORK REWORK RECEIPT',
            'JOB WORK RATE MASTER',
            'SUB-CONTRACTOR RATING PARAMETERS',
            'JOB WORK REPORTS',
            'INVENTORY',
            'GRN (GOODS RECEIPT NOTE)',
            'MATERIAL ISSUE',
            'GIR (GATE INWARD RECEIPT)',
            'OPENING STOCK',
            'TRANSACTION',
            'STOCK TRANSFER ITEM TO ITEM',
            'STOCK TRANSFER BETWEEN STORES',
            'STOCK TRANSFER BETWEEN GODOWNS',
            'ITEM STOCK STATUS',
            'FINISH ITEM STOCK STATUS',
            'MATERIAL ISSUE AGAINST PROJECT',
            'RETURNABLE/NON-RETURNABLE CHALLAN',
            'GRN MODIFICATION',
            'GRN ITEM SERIAL NO.',
            'GRN VIEW',
            'MATERIAL ISSUE MULTILEVEL',
            'ISSUE MATERIAL AGAINST SO',
            'BATCH/HEAT NO. TRACKING',
            'SERIAL NO. TRACKING',
            'GATE OUTWARD NOTE',
            'INVENOTY REPORTS',
            'QUALITY CONTROL',
            'INWARD QC',
            'FINISH GOOD QC',
            'WORK ORDER SUB-ASSEMBLY QC',
            'ASSEMBLY CARD QC',
            'JOB CARD PROCESS (IN SIDE) QC',
            'JOB WORK (OUT SIDE)',
            'MATERIAL RETURN FROM JOB CARD QC',
            'MATERIAL RETURN FROM SUB-CONTRACTOR QC',
            'INWARD QC MODIFICATION',
            'FINISH GOODS QC MODIFICATION',
            'JOB WORK (OUT SIDE) QC MODIFICATION',
            'FINISH GOODS QC AGAINST SO',
            'INSTRUMENT CATEGORY',
            'INSTRUMENT MASTER',
            'ISSUE INSTRUMENTS',
            'JIGS & FIXTURES CATEGORY',
            'JIGS & FIXTURES MASTER',
            'RAW MATERIAL TC',
            'JOB CARD INSIDE TC',
            'JOB CARD OUTSIDE TC',
            'WORK ORDER REJECTED ITEMS',
            'ROUTINE TEST',
            'TRANSACTION MACHINE TEST',
            'QC REPORTS',
            'DESPATCH',
            'GENERATE INVOICE',
            'TRANSFER CHALLAN & INVOICE',
            'DESPATCH INTIMATION',
            'TAX FORM DETAILS',
            'DESPATCH FOLLOW UP',
            'SERVICE INVOICE',
            'DEALER INVOICE',
            'SUPPLEMENTARY INVOICE',
            'DEALER SALES ENTRY',
            'DESPATCH REPORTS',
            'SERVICE',
            'COMPLAINT TYPE MASTER',
            'SERVICE CONTRACT MASTER',
            'SERVICE CALL/COMPLAINT',
            'ERECTION & COMMISSIONING',
            'FEEDBACK QUESTION MASTER',
            'FEEDBACK ANSWER MASTER',
            'FEEDBACK TEMPLATE',
            'SERVICE REPORT',
            'FIXED ASSETS',
            'FIXED ASSETS MASTER',
            'ASSETS LOCATION MASTER',
            'MAINTENANCE SERVICE DETAILS',
            'INSURANCE DETAILS',
            'FIXED ASSETS REPORTS',
            'FINANCE',
            'FINANCE MASTER',
            'CHART OF ACCOUNT (GROUPS)',
            'GENERAL LEDGER ACCOUNTS',
            'CHEQUE PRINTING REPORT PARAMETER',
            'TDS MASTER',
            'PAYMENT MODE MASTER',
            'NARRATION MASTER',
            'BUDGET MASTER',
            'ACCOUNT PARAMETERS',
            'COST CENTER GROUP MASTER',
            'RECEIVABLES',
            'RECEIVABLES (MULTIPLE ENTRY)',
            'RECEIVABLES ADVANCE',
            'PAYMENTS',
            'PAYMENTS (MULTIPLE ENTRY)',
            'JOURNAL',
            'JOURNAL (MULTIPLE ENTRY)',
            'CONTRA',
            'CREDIT NOTE',
            'DEBIT NOTE',
            'BANK RECONCILIATION',
            'GENERAL LEDGER',
            'DAY BOOK',
            'ACCOUNT BALANCE SUMMARY',
            'TDS SUMMARY',
            'FOREX GAIN LOSS PROJECTION',
            'TRIAL BALANCE',
            'BALANCE SHEET',
            'PROFIT & LOSS',
            'DEPRECATION REGISTER INCOME TAX ACT.',
            'DEPRECATION REGISTER COMPANY ACT.',
            'BUDGET SUMMARY',
            'COST CENTER SUMMARY',
            'COST CENTER LEDGER',
            'FINANCE REPORTS',
            'MIS REPORTS',
            'LIST OF ENQUIRY',
            'LIST OF QUOTATION',
            'QUOTATION SUMMARY (MIS)',
            'SALES ACTIVITY',
            'SALES ORDER SUMMARY',
            'SALES ORDER SUMMARY (MIS)',
            'SALES SUMMARY',
            'SALES SUMMARY (MIS)',
            'MIS SALES (ENQ, QTN, SO, INV)',
            'SALES AGENT PERFORMANCE REPORT',
            'SALES TARGET SUMMARY',
            'SALES TARGET SUMMARY (GROUP WISE)',
            'DESPATCH SUMMARY',
            'ACTUAL COST VS INVOICE RATE',
            'WORK ORDER LIST',
            'PURCHASE SUMMARY',
            'LIST OF PARTY',
            'LIST OF ITEMS',
            'SALES REGISTER',
            'PURCHASE REGISTER',
            'DELAY QUOTATION',
            'DELIVERY ANALYSIS',
            'WORK ORDER PRINTING',
            'WORK ORDER SHORTAGE REPORT',
            'GRAPHICAL REPORTS',
            'ENQUIRY GRAPH',
            'SALES ORDER GRAPH',
            'SALES GRAPH',
            'RECEIVABLES VS PAYMENT GRAPH',
            'PURCHASE GRAPH',
            'STOCK GRAPH',
            'BUSINESS GRAPH',
            'STATUTORY REPORTS',
            'GST RETURN',
            'GST SUMMARY SALES',
            'GST SUMMARY PURCHASE',
            'GST ITC-04',
            'FORM 201A',
            'FORM 201B',
            'FORM 201C',
            'FORM 201C GROUP WISE',
            'FORM 201E E-RETURN',
            'CST E-RETURN',
            'DEALER E-RETURN',
            'UTILITY',
            'ACTIVITY TYPE MASTER',
            'ACTIVITY/ALERT TYPE MASTER',
            'COURIER TYPE',
            'COURIER MANAGEMENT',
            'DAILY WORK SUMMARY',
            'DAILY WORK ENTRY',
            'DAILY WORK SUMMARY USER',
            'UTILITY REPORT',
            'ADMINISTRATION & SETUP',
            'COMPANY',
            'USER MANAGEMENT',
            'REPORT PARAMETERS',
            'REPORT DESIGNING',
            'BACKUP',
            'SALES PURCHASE FILE FOR ACCOUNTING',
            'AUTO MAIL PARAMETERS',
            'VIEW LOGIN USERS',
            'EXCISE',
            'RG1 DAILY PRODUCTION',
            'RG1 DAILY PRODUCTION ITEM WISE',
            'PERSONAL LEDGER ACCOUNT (PLA)',
            'RG 23A PART1',
            'RG 23A PART2',
            'RG 23C PART1',
            'RG 23C PART2',
            'SERVICE TAX CREDIT ACCOUNTS',
            'G.A.R.-7 CHALLAN',
            'ANNEXURE - IV',
            'HR MASTER',
            'GRADE MASTER',
            'HR BRANCH MASTER',
            'DEPARTMENT MASTER',
            'DIVISION MASTER',
            'UNIT MASTER',
            'CATEGORY MASTER',
            'GROUP MASTER',
            'DESIGNATION MASTER'
        ]);*/

        $permissions = [
            [
                "text" => "MASTER",
                "isParent" => true,
                "children" => [
                    [
                        "text" => "GENERAL MASTER",
                        "isParent" => true,
                        "children" => [
                            ["text" => "UOM MASTER"],
                            ["text" => "ITEM MAKE MASTER"],
                            ["text" => "STORE MASTER"],
                            ["text" => "TEST CERTIFICATE TYPE"],
                            ["text" => "PARTY TYPE"],
                            ["text" => "BUSINESS TYPE MASTER"],
                            ["text" => "COUNTRY MASTER"],
                            ["text" => "STATE MASTER"],
                            ["text" => "CITY MASTER"],
                            ["text" => "CURRENCY MASTER"],
                            ["text" => "DEPARTMENT"],
                            ["text" => "DESIGNATION"],
                            ["text" => "ENQUIRY REFERENCE MASTER"],
                            ["text" => "QUOTATION TYPE"],
                            ["text" => "SALES STAGE TITLE MASTER"],
                            ["text" => "SALES LEAD TITLE MASTER"],
                            ["text" => "INDUSTRIES TYPE MASTER"],
                            ["text" => "REASON MASTER"],
                            ["text" => "PURCHASE TYPE"],
                            ["text" => "DOCUMENT HEADER"],
                            ["text" => "DOCUMENT FOOTER"],
                            ["text" => "NOTE MASTER"],
                            ["text" => "MACHINE MASTER"],
                            ["text" => "PROCESS MASTER"],
                            ["text" => "OPERATOR MASTER"],
                            ["text" => "BANK MASTER"],
                            ["text" => "PACKING MASTER"],
                            ["text" => "PAYMENT DEDUCTION MASTER"],
                            ["text" => "EXPENSE MASTER"],
                            ["text" => "DOCUMENT TYPE MASTER"],
                            ["text" => "BRANCH MASTER"],
                        ],
                    ],
                    [
                        "text" => "PARTY MASTER",
                        "isParent" => true,
                        "children" => [
                            ["text" => "Add - PARTY MASTER"],
                            ["text" => "Edit - PARTY MASTER"],
                            ["text" => "Update - PARTY MASTER"],
                            ["text" => "Delete - PARTY MASTER"],
                            ["text" => "Approve - PARTY MASTER"],
                        ],
                    ],
                    ["text" => "PARTY GROUP MASTER"],
                    ["text" => "INVOICE TYPE MASTER"],
                    ["text" => "SALES ORDER TYPE MASTER"],
                    [
                        "text" => "ITEM MASTER",
                        "isParent" => true,
                        "children" => [
                            ["text" => "Add - ITEM MASTER"],
                            ["text" => "Edit - ITEM MASTER"],
                            ["text" => "Update - ITEM MASTER"],
                            ["text" => "Delete - ITEM MASTER"],
                            ["text" => "Copy - ITEM MASTER"],
                        ],
                    ],
                    ["text" => "ITEM CATEGORY"],
                    ["text" => "ITEM GROUP"],
                    ["text" => "MAIN GROUP/SUB GROUP"],
                    ["text" => "HSN/SAC MASTER"],
                    ["text" => "MATERIAL SPECIFICATION"],
                    ["text" => "BILLING DESCRIPTION MASTER"],
                    ["text" => "BILLING TEMPLATE MASTER"],
                    ["text" => "ADDON TYPE"],
                    ["text" => "ADDON DETAIL"],
                    ["text" => "ITEM SERIAL NO GENERATION PARAMETERS"],
                    ["text" => "SALES TARGET ITEM GROUP"],
                    ["text" => "TERM & CONDITION GROUP"],
                    ["text" => "TERM & CONDITION DETAILS"],
                    ["text" => "DEFAULT TERM & CONDITION"],
                    ["text" => "TERM & CONDITION TEMPLATE"],
                    ["text" => "TAX MASTER"],
                    ["text" => "TAX FORMS"],
                    ["text" => "ISO/API DOCUMENT"],
                    ["text" => "DUTY DRAWBACK TARIFF MASTER"],
                    ["text" => "IMPORT ITEM MASTER FROM EXCEL"],
                    ["text" => "IMPORT PARTY MASTER FROM EXCEL"],
                    ["text" => "TASK MANAGER"],
                    ["text" => "PROGRESS STAGE MASTER"],
                    ["text" => "SERIAL MASTER"],
                    ["text" => "MASTER REPORTS"],
                ],
            ],
            [
                "text" => "SALES & CRM",
                "isParent" => true,
                "children" => [
                    ["text" => "SALES SUPPORT"],
                    ["text" => "SALES OPPORTUNITIES/LEADS"],
                    ["text" => "SALES ENQUIRY"],
                    ["text" => "SALES QUOTATION"],
                    ["text" => "SALES QUOTATION APPROVAL"],
                    ["text" => "SALES ORDER"],
                    ["text" => "PROFORMA INVOICE"],
                    ["text" => "SALES RETURN - CREDIT NOTE"],
                    ["text" => "SALES BRANCHES"],
                    ["text" => "SALES OFFICES"],
                    ["text" => "SALES COSTING MASTER"],
                    ["text" => "SALES COSTING TEMPLATES"],
                    ["text" => "SALES DATA HISTORY"],
                    ["text" => "SALES TARGET"],
                    ["text" => "ITEM RATE MATER"],
                    ["text" => "PRICE LIST (PARTY TYPE)"],
                    ["text" => "PRICE LIST (PARTY TYPE - ITEM WISE)"],
                    ["text" => "PRICE LIST TYPE MASTER"],
                    ["text" => "PRICE LIST TYPE WISE"],
                    ["text" => "PAYMENT RECEIPT"],
                    ["text" => "PROJECT MANAGEMENT"],
                    ["text" => "COMPETITOR MASTER"],
                    ["text" => "SALES REPORTS"],
                ],
            ],
            [
                "text" => "PRODUCTION PLANNING",
                "isParent" => true,
                "children" => [
                    ["text" => "WORK ORDER"],
                    ["text" => "JOB CARD"],
                    ["text" => "PROCESS SHEET"],
                    ["text" => "ASSEMBLY CARD"],
                    ["text" => "ITEM REQUISITION"],
                    ["text" => "ADVANCE PLANNING"],
                    ["text" => "PRODUCTION FORECASTING"],
                    ["text" => "APPROVE WORK ORDER FOR PRODUCTION"],
                    ["text" => "JOB CARD MATERIAL RETURN FROM SHOP"],
                    ["text" => "JOB CARD PROCESS SUMMARY"],
                    ["text" => "WORK ORDER PROCESS SUMMARY"],
                    ["text" => "WORK ORDER ITEM SERIAL NOS."],
                    ["text" => "GENERATE WO AGAINST SO"],
                    ["text" => "CANCEL/SHORT CLOSE WORK ORDER AGAINST SO"],
                    ["text" => "PRODUCTION PLANNING REPORTS"],
                ],
            ],
            [
                "text" => "ENGINEERING & BOM",
                "isParent" => true,
                "children" => [
                    ["text" => "BILL OF MATERIAL"],
                    ["text" => "REPLACE ITEM IN BOM"],
                    ["text" => "REPLACE SALES ORDER ITEMS"],
                    ["text" => "DRAWING MASTER"],
                    ["text" => "BOM REPORTS"],
                ],
            ],
            [
                "text" => "MRP",
                "isParent" => true,
                "children" => [
                    ["text" => "WO SHORTAGE (PURCHASE ITEMS) - CUMULATIVE"],
                    ["text" => "WO SHORTAGE (ASSEMBLY/COMPONENTS) - CUMULATIVE"],
                    ["text" => "MINIMUM LEVEL SHORTAGE"],
                    ["text" => "MANUAL PLANNING"],
                    ["text" => "WO SHORTAGE (PURCHASE ITEMS) - WO WISE"],
                    ["text" => "WO SHORTAGE (ASSEMBLY/COMPONENTS) - WO WISE"],
                    ["text" => "PENDING INDENT"],
                    ["text" => "INDENT APPROVAL"],
                    ["text" => "FORECAST BASE SHORTAGE"],
                    ["text" => "MRP REPORT"],
                ],
            ],
            [
                "text" => "PURCHASE",
                "isParent" => true,
                "children" => [
                    ["text" => "PURCHASE ORDER AGAINST INDENT"],
                    ["text" => "PURCHASE ORDER"],
                    ["text" => "PURCHASE ORDER APPROVAL"],
                    ["text" => "PURCHASE COSTING"],
                    ["text" => "PURCHASE RETURN - DEBIT NOTE"],
                    ["text" => "PURCHASE CARD (ITEM WISE)"],
                    ["text" => "PURCHASE CARD (PARTY WISE)"],
                    ["text" => "ITEM RATE MASTER (PURCHASE)"],
                    ["text" => "VENDOR RATING PARAMETERS"],
                    ["text" => "PURCHASE ENQUIRY"],
                    ["text" => "PURCHASE QUOTATION"],
                    ["text" => "PURCHASE REPORT"],
                ],
            ],
            [
                "text" => "JOB WORK",
                "isParent" => true,
                "children" => [
                    ["text" => "JOB WORK ORDER"],
                    ["text" => "ISSUE (JOB WORK CHALLAN)"],
                    ["text" => "RECEIPT (JOB WORK CHALLAN)"],
                    ["text" => "RAW MATERIAL RETURN FROM SUB - CONTRACTOR"],
                    ["text" => "SCRAP RECEIPT ENTRY"],
                    ["text" => "JOB WORK REWORK CHALLAN"],
                    ["text" => "JOB WORK REWORK RECEIPT"],
                    ["text" => "JOB WORK RATE MASTER"],
                    ["text" => "SUB-CONTRACTOR RATING PARAMETERS"],
                    ["text" => "JOB WORK REPORTS"],
                ],
            ],
            [
                "text" => "INVENTORY",
                "isParent" => true,
                "children" => [
                    ["text" => "GRN (GOODS RECEIPT NOTE)"],
                    ["text" => "MATERIAL ISSUE"],
                    ["text" => "GIR (GATE INWARD RECEIPT)"],
                    ["text" => "OPENING STOCK"],
                    ["text" => "TRANSACTION"],
                    ["text" => "STOCK TRANSFER ITEM TO ITEM"],
                    ["text" => "STOCK TRANSFER BETWEEN STORES"],
                    ["text" => "STOCK TRANSFER BETWEEN GODOWNS"],
                    ["text" => "ITEM STOCK STATUS"],
                    ["text" => "FINISH ITEM STOCK STATUS"],
                    ["text" => "MATERIAL ISSUE AGAINST PROJECT"],
                    ["text" => "RETURNABLE/NON-RETURNABLE CHALLAN"],
                    ["text" => "GRN MODIFICATION"],
                    ["text" => "GRN ITEM SERIAL NO."],
                    ["text" => "GRN VIEW"],
                    ["text" => "MATERIAL ISSUE MULTILEVEL"],
                    ["text" => "ISSUE MATERIAL AGAINST SO"],
                    ["text" => "BATCH/HEAT NO. TRACKING"],
                    ["text" => "SERIAL NO. TRACKING"],
                    ["text" => "GATE OUTWARD NOTE"],
                    ["text" => "INVENOTY REPORTS"],
                ],
            ],
            [
                "text" => "QUALITY CONTROL",
                "isParent" => true,
                "children" => [
                    ["text" => "INWARD QC"],
                    ["text" => "FINISH GOOD QC"],
                    ["text" => "WORK ORDER SUB-ASSEMBLY QC"],
                    ["text" => "ASSEMBLY CARD QC"],
                    ["text" => "JOB CARD PROCESS (IN SIDE) QC"],
                    ["text" => "JOB WORK (OUT SIDE)"],
                    ["text" => "MATERIAL RETURN FROM JOB CARD QC"],
                    ["text" => "MATERIAL RETURN FROM SUB-CONTRACTOR QC"],
                    ["text" => "INWARD QC MODIFICATION"],
                    ["text" => "FINISH GOODS QC MODIFICATION"],
                    ["text" => "JOB WORK (OUT SIDE) QC MODIFICATION"],
                    ["text" => "FINISH GOODS QC AGAINST SO"],
                    ["text" => "INSTRUMENT CATEGORY"],
                    ["text" => "INSTRUMENT MASTER"],
                    ["text" => "ISSUE INSTRUMENTS"],
                    ["text" => "JIGS & FIXTURES CATEGORY"],
                    ["text" => "JIGS & FIXTURES MASTER"],
                    ["text" => "RAW MATERIAL TC"],
                    ["text" => "JOB CARD INSIDE TC"],
                    ["text" => "JOB CARD OUTSIDE TC"],
                    ["text" => "WORK ORDER REJECTED ITEMS"],
                    ["text" => "ROUTINE TEST"],
                    ["text" => "TRANSACTION MACHINE TEST"],
                    ["text" => "QC REPORTS"],
                ],
            ],
            [
                "text" => "DESPATCH",
                "isParent" => true,
                "children" => [
                    ["text" => "GENERATE INVOICE"],
                    ["text" => "TRANSFER CHALLAN & INVOICE"],
                    ["text" => "DESPATCH INTIMATION"],
                    ["text" => "TAX FORM DETAILS"],
                    ["text" => "DESPATCH FOLLOW UP"],
                    ["text" => "SERVICE INVOICE"],
                    ["text" => "DEALER INVOICE"],
                    ["text" => "SUPPLEMENTARY INVOICE"],
                    ["text" => "DEALER SALES ENTRY"],
                    ["text" => "DESPATCH REPORTS"],
                ],
            ],
            [
                "text" => "SERVICE",
                "isParent" => true,
                "children" => [
                    ["text" => "COMPLAINT TYPE MASTER"],
                    ["text" => "SERVICE CONTRACT MASTER"],
                    ["text" => "SERVICE CALL/COMPLAINT"],
                    ["text" => "ERECTION & COMMISSIONING"],
                    ["text" => "FEEDBACK QUESTION MASTER"],
                    ["text" => "FEEDBACK ANSWER MASTER"],
                    ["text" => "FEEDBACK TEMPLATE"],
                    ["text" => "SERVICE REPORT"],
                ],
            ],
            [
                "text" => "FIXED ASSETS",
                "isParent" => true,
                "children" => [
                    ["text" => "FIXED ASSETS MASTER"],
                    ["text" => "ASSETS LOCATION MASTER"],
                    ["text" => "MAINTENANCE SERVICE DETAILS"],
                    ["text" => "INSURANCE DETAILS"],
                    ["text" => "FIXED ASSETS REPORTS"],
                ],
            ],
            [
                "text" => "FINANCE",
                "isParent" => true,
                "children" => [
                    [
                        "text" => "FINANCE MASTER",
                        "isParent" => true,
                        "children" => [
                            ["text" => "CHART OF ACCOUNT (GROUPS)"],
                            ["text" => "GENERAL LEDGER ACCOUNTS"],
                            ["text" => "CHEQUE PRINTING REPORT PARAMETER"],
                            ["text" => "TDS MASTER"],
                            ["text" => "PAYMENT MODE MASTER"],
                            ["text" => "NARRATION MASTER"],
                            ["text" => "BUDGET MASTER"],
                            ["text" => "ACCOUNT PARAMETERS"],
                            ["text" => "COST CENTER GROUP MASTER"],
                        ],
                    ],
                    ["text" => "RECEIVABLES"],
                    ["text" => "RECEIVABLES (MULTIPLE ENTRY)"],
                    ["text" => "RECEIVABLES ADVANCE"],
                    ["text" => "PAYMENTS"],
                    ["text" => "PAYMENTS (MULTIPLE ENTRY)"],
                    ["text" => "JOURNAL"],
                    ["text" => "JOURNAL (MULTIPLE ENTRY)"],
                    ["text" => "CONTRA"],
                    ["text" => "CREDIT NOTE"],
                    ["text" => "DEBIT NOTE"],
                    ["text" => "BANK RECONCILIATION"],
                    ["text" => "GENERAL LEDGER"],
                    ["text" => "DAY BOOK"],
                    ["text" => "ACCOUNT BALANCE SUMMARY"],
                    ["text" => "TDS SUMMARY"],
                    ["text" => "FOREX GAIN LOSS PROJECTION"],
                    ["text" => "TRIAL BALANCE"],
                    ["text" => "BALANCE SHEET"],
                    ["text" => "PROFIT & LOSS"],
                    ["text" => "DEPRECATION REGISTER INCOME TAX ACT."],
                    ["text" => "DEPRECATION REGISTER COMPANY ACT."],
                    ["text" => "BUDGET SUMMARY"],
                    ["text" => "COST CENTER SUMMARY"],
                    ["text" => "COST CENTER LEDGER"],
                    ["text" => "FINANCE REPORTS"],
                ],
            ],
            [
                "text" => "MIS REPORTS",
                "isParent" => true,
                "children" => [
                    ["text" => "LIST OF ENQUIRY"],
                    ["text" => "LIST OF QUOTATION"],
                    ["text" => "QUOTATION SUMMARY (MIS)"],
                    ["text" => "SALES ACTIVITY"],
                    ["text" => "SALES ORDER SUMMARY"],
                    ["text" => "SALES ORDER SUMMARY (MIS)"],
                    ["text" => "SALES SUMMARY"],
                    ["text" => "SALES SUMMARY (MIS)"],
                    ["text" => "MIS SALES (ENQ, QTN, SO, INV)"],
                    ["text" => "SALES AGENT PERFORMANCE REPORT"],
                    ["text" => "SALES TARGET SUMMARY"],
                    ["text" => "SALES TARGET SUMMARY (GROUP WISE)"],
                    ["text" => "DESPATCH SUMMARY"],
                    ["text" => "ACTUAL COST VS INVOICE RATE"],
                    ["text" => "WORK ORDER LIST"],
                    ["text" => "PURCHASE SUMMARY"],
                    ["text" => "LIST OF PARTY"],
                    ["text" => "LIST OF ITEMS"],
                    ["text" => "SALES REGISTER"],
                    ["text" => "PURCHASE REGISTER"],
                    ["text" => "DELAY QUOTATION"],
                    ["text" => "DELIVERY ANALYSIS"],
                    ["text" => "WORK ORDER PRINTING"],
                    ["text" => "WORK ORDER SHORTAGE REPORT"],
                ],
            ],
            [
                "text" => "GRAPHICAL REPORTS",
                "isParent" => true,
                "children" => [
                    ["text" => "ENQUIRY GRAPH"],
                    ["text" => "SALES ORDER GRAPH"],
                    ["text" => "SALES GRAPH"],
                    ["text" => "RECEIVABLES VS PAYMENT GRAPH"],
                    ["text" => "PURCHASE GRAPH"],
                    ["text" => "STOCK GRAPH"],
                    ["text" => "BUSINESS GRAPH"],
                ],
            ],
            [
                "text" => "STATUTORY REPORTS",
                "isParent" => true,
                "children" => [
                    ["text" => "GST RETURN"],
                    ["text" => "GST SUMMARY SALES"],
                    ["text" => "GST SUMMARY PURCHASE"],
                    ["text" => "GST ITC-04"],
                    ["text" => "FORM 201A"],
                    ["text" => "FORM 201B"],
                    ["text" => "FORM 201C"],
                    ["text" => "FORM 201C GROUP WISE"],
                    ["text" => "FORM 201E E-RETURN"],
                    ["text" => "CST E-RETURN"],
                    ["text" => "DEALER E-RETURN"],
                ],
            ],
            [
                "text" => "UTILITY",
                "isParent" => true,
                "children" => [
                    ["text" => "ACTIVITY TYPE MASTER"],
                    ["text" => "ACTIVITY/ALERT TYPE MASTER"],
                    ["text" => "COURIER TYPE"],
                    ["text" => "COURIER MANAGEMENT"],
                    ["text" => "DAILY WORK SUMMARY"],
                    ["text" => "DAILY WORK ENTRY"],
                    ["text" => "DAILY WORK SUMMARY USER"],
                    ["text" => "UTILITY REPORT"],
                ],
            ],
            [
                "text" => "ADMINISTRATION & SETUP",
                "isParent" => true,
                "children" => [
                    ["text" => "COMPANY"],
                    ["text" => "USER MANAGEMENT"],
                    ["text" => "REPORT PARAMETERS"],
                    ["text" => "REPORT DESIGNING"],
                    ["text" => "BACKUP"],
                    ["text" => "SALES PURCHASE FILE FOR ACCOUNTING"],
                    ["text" => "AUTO MAIL PARAMETERS"],
                    ["text" => "VIEW LOGIN USERS"],
                ],
            ],
            [
                "text" => "EXCISE",
                "isParent" => true,
                "children" => [
                    ["text" => "RG1 DAILY PRODUCTION"],
                    ["text" => "RG1 DAILY PRODUCTION ITEM WISE"],
                    ["text" => "PERSONAL LEDGER ACCOUNT (PLA)"],
                    ["text" => "RG 23A PART1"],
                    ["text" => "RG 23A PART2"],
                    ["text" => "RG 23C PART1"],
                    ["text" => "RG 23C PART2"],
                    ["text" => "SERVICE TAX CREDIT ACCOUNTS"],
                    ["text" => "G.A.R.-7 CHALLAN"],
                    ["text" => "ANNEXURE - IV"],
                ],
            ],
            [
                "text" => "HR MASTER",
                "isParent" => true,
                "children" => [
                    ["text" => "GRADE MASTER"],
                    ["text" => "HR BRANCH MASTER"],
                    ["text" => "DEPARTMENT MASTER"],
                    ["text" => "DIVISION MASTER"],
                    ["text" => "UNIT MASTER"],
                    ["text" => "CATEGORY MASTER"],
                    ["text" => "GROUP MASTER"],
                    ["text" => "DESIGNATION MASTER"],
                ],
            ],
        ];
        $this->createPermissions($permissions);


        /*$permissions->each(fn($permission): array => [
            Permission::create([
                'name' => $permission,
                'guard_name' => 'api'
            ]),
            Permission::create([
                'name' => $permission,
                'guard_name' => 'web'
            ]),
        ]);

        $admin = Role::firstOrCreate([
            'name' => UserTypeEnums::ADMIN,
            'guard_name' => 'api'
        ]);
        $admin->givePermissionTo($permissions->all());

        $admin = Role::firstOrCreate([
            'name' => UserTypeEnums::ADMIN,
            'guard_name' => 'web'
        ]);
        $admin->givePermissionTo($permissions->all());

        Role::firstOrCreate([
            'name' => UserTypeEnums::USER,
            'guard_name' => 'api'
        ]);

        Role::firstOrCreate([
            'name' => UserTypeEnums::USER,
            'guard_name' => 'web'
        ]);

        Role::firstOrCreate([
            'name' => UserTypeEnums::HODADMIN,
            'guard_name' => 'api'
        ]);
        Role::firstOrCreate([
            'name' => UserTypeEnums::HODADMIN,
            'guard_name' => 'web'
        ]);

        Role::firstOrCreate([
            'name' => UserTypeEnums::EMPLOYEE,
            'guard_name' => 'api'
        ]);
        Role::firstOrCreate([
            'name' => UserTypeEnums::EMPLOYEE,
            'guard_name' => 'web'
        ]);
        Role::firstOrCreate([
            'name' => UserTypeEnums::HRADMIN,
            'guard_name' => 'api'
        ]);
        Role::firstOrCreate([
            'name' => UserTypeEnums::HRADMIN,
            'guard_name' => 'web'
        ]);*/


    }

    public function createPermissions(array $permissions) {
        $permissions = collect($permissions);
        $permissions->each(function ($permission) {
            Log::info($permission['text']);
            if (isset($permission['isParent']) && $permission['isParent'] === true) {
                $this->createPermissions($permission['children']);
            }
        });
    }
}
